name: example-environment
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - pip
  - pip:
    - nbgitpuller
    - pandas
    - matplotlib
    - seaborn
    - solara
    - mesa[rec]==3.0.0b1
